version: "3.7"
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=lyvel
            - POSTGRES_PASSWORD=lyvel
            - POSTGRES_DB=lyvel
        ports:
            - "5443:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
